proxy:
  build: identiproxy/
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=46.146.181.99
    - NGINX_PROXY=http://identidock:9090

identidock:
  build: identidock/
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD

dnmonster:
  image: amouat/dnmonster

redis:
  image: redis

logspout:
  image: amouat/logspout-logstash
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock #Монтирование Docker-сокета, для того чтобы Logspout мог установить соединение с Docker API
  links:
    - logstash
  command: logstash://logstash:5000

logstash:
  image: logstash:6.8.8
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  environment:
    LOGSPOUT: ignore
  links:
    - elasticsearch
  command: -f /etc/logstash.conf

elasticsearch:
  image: elasticsearch:6.8.8
  environment:
    LOGSPOUT: ignore

kibana:
  image: kibana:6.8.8
  environment:
    LOGSPOUT: ignore
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "5601:5601"

#sudo sysctl -w vm.max_map_count=262144
#docker-compose -f prod-with-logging.yml -p proxy build
#docker-compose -f prod-with-logging.yml -p proxy up -d
#docker-compose -f prod-with-logging.yml -p proxy stop

#docker run -d --name cadvisor -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys:ro -v /var/lib/docker/:/var/lib/docker:ro -p 8080:8080 google/cadvisor:latest
#docker run -d --name prometheus -p 9090:9090 -v $(pwd)/prometheus.conf:/prometheus.conf --link cadvisor:cadvisor prom/prometheus --config.file=/prometheus.conf
#filter fro prometheus sum(container_cpu_usage_seconds_total{name=~"proxy.*"}) by (name)