identidock: #Имя создаваемого контейнера
  build: . #Каталог расположения Dockerfile
  ports: #Проброска портов из контейнера
    - "5001:5000"
  environment: #Перемсенные окружения внутри контейнера
    ENV: DEV
  volumes: #Монтирование папки хоста для контейнера
    - ./app:/app
